import {
  User, Department, Company, VisitorCategory, ContractorCategory,
  MeetingVenue, Visitor, Contractor, BlacklistEntry, AuditLog,
  LoginHistory, SystemSettings, PasswordPolicy, EmailLogEntry
} from '../types';

export interface DataStore {
  users: User[];
  departments: Department[];
  companies: Company[];
  visitorCategories: VisitorCategory[];
  contractorCategories: ContractorCategory[];
  meetingVenues: MeetingVenue[];
  visitors: Visitor[];
  contractors: Contractor[];
  blacklist: BlacklistEntry[];
  auditLogs: AuditLog[];
  loginHistory: LoginHistory[];
  settings: SystemSettings;
  passwordPolicy: PasswordPolicy;
  activeUserId: string;
  emailLogs: EmailLogEntry[];
}

const now = new Date();
const todayStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;

export const db: DataStore = {
  activeUserId: 'usr-admin-1',
  emailLogs: [],

  users: [
    {
      id: 'usr-admin-1',
      username: 'admin',
      fullName: 'Evelyn Reed',
      email: 'evelyn.reed@enterprise.internal',
      role: 'ADMINISTRATOR',
      departmentId: 'dept-it',
      departmentName: 'Information Technology',
      companyId: 'comp-internal',
      isActive: true,
      lastLoginAt: new Date().toISOString(),
      badgeId: 'ADM-001',
      phone: '+1 (555) 019-2831'
    },
    {
      id: 'usr-md-1',
      username: 'managing_director',
      fullName: 'Tanaka Kenji (Managing Director)',
      email: 'tanaka.kenji@enterprise.internal',
      role: 'MANAGING_DIRECTOR',
      departmentId: 'dept-exec',
      departmentName: 'Executive Directorate',
      companyId: 'comp-internal',
      isActive: true,
      lastLoginAt: new Date().toISOString(),
      badgeId: 'MD-001',
      phone: '+1 (555) 011-9900'
    },
    {
      id: 'usr-staff-1',
      username: 'staff_john',
      fullName: 'John Miller',
      email: 'john.miller@enterprise.internal',
      role: 'STAFF',
      departmentId: 'dept-it',
      departmentName: 'Information Technology',
      companyId: 'comp-internal',
      isActive: true,
      lastLoginAt: new Date().toISOString(),
      badgeId: 'STF-104',
      phone: '+1 (555) 014-9921'
    },
    {
      id: 'usr-staff-2',
      username: 'staff_sarah',
      fullName: 'Sarah Jenkins',
      email: 'sarah.jenkins@enterprise.internal',
      role: 'STAFF',
      departmentId: 'dept-hr',
      departmentName: 'Human Resources',
      companyId: 'comp-internal',
      isActive: true,
      lastLoginAt: new Date().toISOString(),
      badgeId: 'STF-208',
      phone: '+1 (555) 018-3342'
    },
    {
      id: 'usr-sec-1',
      username: 'sec_officer1',
      fullName: 'Officer Alex Rivera',
      email: 'alex.rivera@enterprise.internal',
      role: 'SECURITY',
      departmentId: 'dept-fac',
      departmentName: 'Facility Management & Security',
      companyId: 'comp-internal',
      isActive: true,
      lastLoginAt: new Date().toISOString(),
      badgeId: 'SEC-801',
      phone: '+1 (555) 012-7711'
    },
    {
      id: 'usr-sec-2',
      username: 'sec_officer2',
      fullName: 'Officer Marcus Vance',
      email: 'marcus.vance@enterprise.internal',
      role: 'SECURITY',
      departmentId: 'dept-fac',
      departmentName: 'Facility Management & Security',
      companyId: 'comp-internal',
      isActive: true,
      lastLoginAt: new Date().toISOString(),
      badgeId: 'SEC-802',
      phone: '+1 (555) 012-7712'
    },
    {
      id: 'usr-prod-1',
      username: 'luqman',
      fullName: 'Luqman (Production Manager)',
      email: 'IT@tanaka.com.my',
      role: 'STAFF',
      departmentId: 'dept-prod',
      departmentName: 'Production',
      companyId: 'comp-internal',
      isActive: true,
      lastLoginAt: new Date().toISOString(),
      badgeId: 'PM-001',
      phone: '+60 12-345 6789'
    }
  ],

  departments: [
    { id: 'dept-it', code: 'IT', name: 'Information Technology', headOfDepartment: 'Robert Zhao', floorLevel: 'Level 4', isActive: true },
    { id: 'dept-hr', code: 'HR', name: 'Human Resources', headOfDepartment: 'Amanda Smith', floorLevel: 'Level 2', isActive: true },
    { id: 'dept-fin', code: 'FIN', name: 'Finance & Accounting', headOfDepartment: 'David Chen', floorLevel: 'Level 3', isActive: true },
    { id: 'dept-fac', code: 'FAC', name: 'Facility Management & Security', headOfDepartment: 'Officer Alex Rivera', floorLevel: 'Ground Floor Guard Desk', isActive: true },
    { id: 'dept-leg', code: 'LEG', name: 'Legal & Compliance', headOfDepartment: 'Patricia Vance', floorLevel: 'Level 5', isActive: true },
    { id: 'dept-prod', code: 'PROD', name: 'Production', headOfDepartment: 'Luqman', floorLevel: 'Prod 1 / Prod 2', isActive: true },
  ],

  companies: [
    { id: 'comp-internal', name: 'Enterprise Headquarters Corp', registrationNumber: 'HQ-883921', companyType: 'INTERNAL', contactPhone: '+1 555-0100', contactEmail: 'info@enterprise.internal', address: '100 Enterprise Way, Tower A', isActive: true, departmentId: 'dept-it', departmentName: 'Information Technology', registeredByUserName: 'System Admin', createdAt: '2026-01-10' },
    { id: 'comp-ext-1', name: 'CyberShield Systems Inc.', registrationNumber: 'CS-90211', companyType: 'CONTRACTOR_VENDOR', contactPhone: '+1 555-0219', contactEmail: 'contact@cybershield.com', address: '45 Tech Plaza, Suite 300', isActive: true, departmentId: 'dept-it', departmentName: 'Information Technology', registeredByUserName: 'John Miller', createdAt: '2026-02-14' },
    { id: 'comp-ext-2', name: 'Acme Global Consulting', registrationNumber: 'ACME-4402', companyType: 'VISITOR_ORGANIZATION', contactPhone: '+1 555-0312', contactEmail: 'support@acmeglobal.com', address: '12 Financial Center', isActive: true, departmentId: 'dept-it', departmentName: 'Information Technology', registeredByUserName: 'John Miller', createdAt: '2026-03-01' },
    { id: 'comp-ext-3', name: 'CleanPro Facility Solutions', registrationNumber: 'CP-11094', companyType: 'CONTRACTOR_VENDOR', contactPhone: '+1 555-0488', contactEmail: 'dispatch@cleanpro.com', address: '88 Industrial Parkway', isActive: true, departmentId: 'dept-fac', departmentName: 'Facility Management & Security', registeredByUserName: 'Officer Alex Rivera', createdAt: '2026-03-15' },
    { id: 'comp-apx', name: 'Apex Global Solutions', registrationNumber: 'COMP-APX-880', companyType: 'VISITOR_ORGANIZATION', contactPhone: '+60 3-8890 1100', contactEmail: 'contact@apexglobal.com', address: 'Level 18, Apex Tech Tower, Cyberjaya', isActive: true, departmentId: 'dept-it', departmentName: 'Information Technology', registeredByUserName: 'John Miller', createdAt: '2026-04-02' },
    { id: 'comp-cyb', name: 'Cyberdyne Security Ltd', registrationNumber: 'COMP-CYB-991', companyType: 'VISITOR_ORGANIZATION', contactPhone: '+60 3-7720 4400', contactEmail: 'info@cyberdyne.io', address: 'Block C, Cyberdyne Park, Bangsar South', isActive: true, departmentId: 'dept-hr', departmentName: 'Human Resources', registeredByUserName: 'Sarah Jenkins', createdAt: '2026-04-10' },
    { id: 'comp-nxg', name: 'NexGen Logistics Corp', registrationNumber: 'COMP-NXG-502', companyType: 'VISITOR_ORGANIZATION', contactPhone: '+60 3-5510 9900', contactEmail: 'ops@nexgenlogistics.com', address: 'Lot 45, Logistics Hub, Port Klang', isActive: true, departmentId: 'dept-fin', departmentName: 'Finance & Procurement', registeredByUserName: 'Finance Dept', createdAt: '2026-05-01' },
    { id: 'comp-cooltech', name: 'CoolTech HVAC Engineering', registrationNumber: 'COMP-CT-9910', companyType: 'CONTRACTOR_VENDOR', contactPhone: '+60 3-8812 9900', contactEmail: 'info@cooltech-hvac.com', address: 'No. 12 Jalan Industri 4, Puchong', isActive: true, departmentId: 'dept-it', departmentName: 'Information Technology', registeredByUserName: 'John Miller', createdAt: '2026-06-12' },
  ],

  visitorCategories: [
    { id: 'vc-1', name: 'Customer', description: 'Clients, corporate guests, and customer business meetings', requiresEscort: false, isActive: true },
    { id: 'vc-2', name: 'Supplier', description: 'Raw material and goods suppliers', requiresEscort: false, isActive: true },
    { id: 'vc-3', name: 'Vendor', description: 'Commercial vendors and solution providers', requiresEscort: false, isActive: true },
    { id: 'vc-4', name: 'Interview', description: 'Job applicants attending talent acquisition interviews', requiresEscort: false, isActive: true },
    { id: 'vc-5', name: 'Government', description: 'State, municipal, and government regulatory officials', requiresEscort: true, isActive: true },
    { id: 'vc-6', name: 'VIP', description: 'High-profile executives, dignitaries & board members', requiresEscort: true, isActive: true },
    { id: 'vc-7', name: 'Delivery', description: 'Courier, parcel delivery & freight handlers', requiresEscort: false, isActive: true },
    { id: 'vc-8', name: 'Maintenance', description: 'Facility, HVAC & office maintenance reps', requiresEscort: false, isActive: true },
    { id: 'vc-9', name: 'Training', description: 'External trainees and workshop participants', requiresEscort: false, isActive: true },
    { id: 'vc-10', name: 'Audit', description: 'Internal & external compliance auditors', requiresEscort: true, isActive: true },
  ],

  contractorCategories: [
    { id: 'cc-1', name: 'Electrical', safetyInductionRequired: true, isActive: true },
    { id: 'cc-2', name: 'Mechanical', safetyInductionRequired: true, isActive: true },
    { id: 'cc-3', name: 'Cleaning', safetyInductionRequired: false, isActive: true },
    { id: 'cc-4', name: 'IT Vendor', safetyInductionRequired: true, isActive: true },
    { id: 'cc-5', name: 'Construction', safetyInductionRequired: true, isActive: true },
    { id: 'cc-6', name: 'Maintenance', safetyInductionRequired: true, isActive: true },
    { id: 'cc-7', name: 'Calibration', safetyInductionRequired: true, isActive: true },
    { id: 'cc-8', name: 'Renovation', safetyInductionRequired: true, isActive: true },
    { id: 'cc-9', name: 'IT Work', safetyInductionRequired: true, isActive: true },
  ],

  meetingVenues: [
    { id: 'mv-1', name: 'Executive Boardroom 1', buildingBlock: 'Tower A', buildingBlocks: ['Tower A'], floorLevel: 'Level 5', floorLevels: ['Level 5'], capacity: 20, isActive: true },
    { id: 'mv-2', name: 'Internal common area & Prod 1 corridor', buildingBlock: 'Prod 1', buildingBlocks: ['Prod 1'], floorLevel: 'Corridor', floorLevels: ['Corridor', 'Common Area'], capacity: 15, isActive: true },
    { id: 'mv-3', name: 'Internal common area & Prod 2 corridor', buildingBlock: 'Prod 2', buildingBlocks: ['Prod 2'], floorLevel: 'Corridor', floorLevels: ['Corridor', 'Common Area'], capacity: 15, isActive: true },
    { id: 'mv-4', name: 'Internal common area & Prod 1 inside', buildingBlock: 'Prod 1', buildingBlocks: ['Prod 1'], floorLevel: 'Inside', floorLevels: ['Inside', 'Prod Floor'], capacity: 12, isActive: true },
    { id: 'mv-5', name: 'Internal common area & Prod 2 inside', buildingBlock: 'Prod 2', buildingBlocks: ['Prod 2'], floorLevel: 'Inside', floorLevels: ['Inside', 'Prod Floor'], capacity: 12, isActive: true },
    { id: 'mv-6', name: 'internal common area & Prod 1 & 2 inside', buildingBlock: 'Prod 1, Prod 2', buildingBlocks: ['Prod 1', 'Prod 2'], floorLevel: 'Inside', floorLevels: ['Inside', 'Common Area'], capacity: 25, isActive: true },
    { id: 'mv-7', name: 'Inside common area & Prod 1 & 2 corridor', buildingBlock: 'Prod 1, Prod 2', buildingBlocks: ['Prod 1', 'Prod 2'], floorLevel: 'Corridor', floorLevels: ['Corridor', 'Inside'], capacity: 20, isActive: true },
    { id: 'mv-8', name: 'MD Room', buildingBlock: 'Executive Block', buildingBlocks: ['Executive Block'], floorLevel: 'Level 3', floorLevels: ['Level 3'], capacity: 8, isActive: true },
    { id: 'mv-9', name: 'Common Area', buildingBlock: 'Main Building', buildingBlocks: ['Main Building'], floorLevel: 'Ground Floor', floorLevels: ['Ground Floor', 'Lobby'], capacity: 50, isActive: true },
  ],

  visitors: [
    {
      id: 'vis-101',
      registrationNo: 'VMS-2026-8801',
      fullName: 'Marcus Vance (Consultant)',
      idNumber: 'A-9812440',
      phone: '+1 555-0192',
      email: 'm.vance@acmeglobal.com',
      companyName: 'Acme Global Consulting',
      visitorCategoryId: 'vc-3',
      visitorCategoryName: 'Vendor',
      purpose: 'System Audit & Compliance Review',
      hostUserId: 'usr-staff-1',
      hostUserName: 'John Miller',
      hostDepartment: 'Information Technology',
      meetingVenueId: 'mv-2',
      meetingVenueName: 'Conference Room B',
      scheduledDate: todayStr,
      scheduledStartTime: '08:00',
      scheduledEndTime: '09:30', // Scheduled end time passed! Active Overstay
      status: 'CHECKED_IN',
      passBadgeNumber: 'V-BADGE-101',
      checkInTime: `${todayStr} 08:05:12`,
      checkOutTime: null,
      checkInSecurityUserId: 'usr-sec-1',
      checkInSecurityUserName: 'Robert Davis (Security)',
      checkOutSecurityUserId: null,
      checkOutSecurityUserName: null,
      vehicleNumber: 'KAA-8819',
      itemsCarried: 'Laptop, External Audit Scanner',
      isBlacklistedAtRegistration: false,
      notes: 'Requires high-security server room access clearance.',
      createdAt: new Date().toISOString()
    },
    {
      id: 'vis-102',
      registrationNo: 'VMS-2026-8802',
      fullName: 'Samantha Wright',
      idNumber: 'B-7718229',
      phone: '+1 555-0482',
      email: 's.wright@cybershield.com',
      companyName: 'CyberShield Systems Inc.',
      visitorCategoryId: 'vc-1',
      visitorCategoryName: 'Customer',
      purpose: 'Q3 Enterprise Strategy Meeting',
      hostUserId: 'usr-staff-1',
      hostUserName: 'John Miller',
      hostDepartment: 'Information Technology',
      meetingVenueId: 'mv-1',
      meetingVenueName: 'Executive Boardroom 1',
      scheduledDate: todayStr,
      scheduledStartTime: '09:00',
      scheduledEndTime: '18:00',
      status: 'CHECKED_IN',
      passBadgeNumber: 'V-BADGE-102',
      checkInTime: `${todayStr} 08:52:00`,
      checkOutTime: null,
      checkInSecurityUserId: 'usr-sec-1',
      checkInSecurityUserName: 'Robert Davis (Security)',
      checkOutSecurityUserId: null,
      checkOutSecurityUserName: null,
      vehicleNumber: 'NYC-4402',
      itemsCarried: 'Presentation Tablet',
      isBlacklistedAtRegistration: false,
      notes: null,
      createdAt: new Date().toISOString()
    },
    {
      id: 'vis-103',
      registrationNo: 'VMS-2026-8803',
      fullName: 'David K. O\'Connor',
      idNumber: 'C-3382910',
      phone: '+1 555-0911',
      email: 'david.oconnor@gov-audit.org',
      companyName: 'State Security Board',
      visitorCategoryId: 'vc-5',
      visitorCategoryName: 'Government',
      purpose: 'Annual Regulatory Facility Inspection',
      hostUserId: 'usr-staff-2',
      hostUserName: 'Sarah Jenkins',
      hostDepartment: 'Human Resources',
      meetingVenueId: 'mv-4',
      meetingVenueName: 'HR Recruitment Suite 202',
      scheduledDate: todayStr,
      scheduledStartTime: '14:00',
      scheduledEndTime: '16:00',
      status: 'SCHEDULED',
      approvalStatus: 'APPROVED',
      approvedByUserId: 'usr-md-1',
      approvedByUserName: 'Tanaka Kenji (Managing Director)',
      approvedAt: `${todayStr} 07:30:00`,
      passBadgeNumber: null,
      checkInTime: null,
      checkOutTime: null,
      checkInSecurityUserId: null,
      checkOutSecurityUserId: null,
      vehicleNumber: null,
      itemsCarried: null,
      isBlacklistedAtRegistration: false,
      notes: 'Government official - Security escort mandatory.',
      createdAt: new Date().toISOString()
    },
    {
      id: 'vis-105',
      registrationNo: 'VMS-2026-8805',
      fullName: 'Marcus Sterling',
      idNumber: 'E-5510294',
      phone: '+1 555-0331',
      email: 'm.sterling@apex-energy.com',
      companyName: 'Apex Energy Partners',
      visitorCategoryId: 'vc-1',
      visitorCategoryName: 'Vendor',
      purpose: 'HVAC Renewal Project Pitch',
      hostUserId: 'usr-staff-1',
      hostUserName: 'John Miller',
      hostDepartment: 'Information Technology',
      meetingVenueId: 'mv-3',
      meetingVenueName: 'IT Innovation Hub',
      scheduledDate: todayStr,
      scheduledStartTime: '15:30',
      scheduledEndTime: '17:00',
      status: 'PENDING_APPROVAL',
      approvalStatus: 'PENDING',
      passBadgeNumber: null,
      checkInTime: null,
      checkOutTime: null,
      checkInSecurityUserId: null,
      checkOutSecurityUserId: null,
      vehicleNumber: 'MY-1120',
      itemsCarried: 'Design Blueprints',
      isBlacklistedAtRegistration: false,
      notes: 'Requires Managing Director executive approval prior to facility entry.',
      createdAt: new Date().toISOString()
    },
    // DUMMY COMPANY 1: Apex Global Solutions (3 Visitors)
    {
      id: 'vis-apx-1',
      registrationNo: 'VMS-2026-7001',
      fullName: 'Alexander Hayes',
      idNumber: 'IC-880112-14-5001',
      phone: '+60 12-388 1122',
      email: 'alexander.hayes@apexglobal.com',
      companyName: 'Apex Global Solutions',
      visitorCategoryId: 'vc-3',
      visitorCategoryName: 'Vendor',
      purpose: 'Enterprise Architecture Consultation',
      hostUserId: 'usr-staff-1',
      hostUserName: 'John Miller',
      hostDepartment: 'Information Technology',
      meetingVenueId: 'mv-2',
      meetingVenueName: 'Conference Room B',
      scheduledDate: todayStr,
      scheduledStartTime: '09:00',
      scheduledEndTime: '17:00',
      status: 'CHECKED_OUT',
      approvalStatus: 'APPROVED',
      passBadgeNumber: 'V-BADGE-701',
      checkInTime: `${todayStr} 08:50:00`,
      checkOutTime: `${todayStr} 16:45:00`,
      checkInSecurityUserId: 'usr-sec-1',
      checkOutSecurityUserId: 'usr-sec-1',
      vehicleNumber: 'W-8812-X',
      itemsCarried: 'MacBook Pro M3 Max, Diagnostic Scanner',
      isBlacklistedAtRegistration: false,
      notes: 'Previous attendee - Apex Lead Consultant',
      createdAt: new Date().toISOString()
    },
    {
      id: 'vis-apx-2',
      registrationNo: 'VMS-2026-7001',
      fullName: 'Beatrice Vance',
      idNumber: 'IC-910520-10-6214',
      phone: '+60 16-554 9011',
      email: 'beatrice.vance@apexglobal.com',
      companyName: 'Apex Global Solutions',
      visitorCategoryId: 'vc-3',
      visitorCategoryName: 'Vendor',
      purpose: 'Enterprise Architecture Consultation',
      hostUserId: 'usr-staff-1',
      hostUserName: 'John Miller',
      hostDepartment: 'Information Technology',
      meetingVenueId: 'mv-2',
      meetingVenueName: 'Conference Room B',
      scheduledDate: todayStr,
      scheduledStartTime: '09:00',
      scheduledEndTime: '17:00',
      status: 'CHECKED_OUT',
      approvalStatus: 'APPROVED',
      passBadgeNumber: 'V-BADGE-702',
      checkInTime: `${todayStr} 08:52:00`,
      checkOutTime: `${todayStr} 16:45:00`,
      checkInSecurityUserId: 'usr-sec-1',
      checkOutSecurityUserId: 'usr-sec-1',
      vehicleNumber: 'V-4410-A',
      itemsCarried: 'iPad Pro 12.9, Presentation Clicker',
      isBlacklistedAtRegistration: false,
      notes: 'Previous attendee - Apex Solution Architect',
      createdAt: new Date().toISOString()
    },
    {
      id: 'vis-apx-3',
      registrationNo: 'VMS-2026-7001',
      fullName: 'Charles Montgomery',
      idNumber: 'IC-850914-08-3329',
      phone: '+60 19-223 8844',
      email: 'charles.montgomery@apexglobal.com',
      companyName: 'Apex Global Solutions',
      visitorCategoryId: 'vc-3',
      visitorCategoryName: 'Vendor',
      purpose: 'Enterprise Architecture Consultation',
      hostUserId: 'usr-staff-1',
      hostUserName: 'John Miller',
      hostDepartment: 'Information Technology',
      meetingVenueId: 'mv-2',
      meetingVenueName: 'Conference Room B',
      scheduledDate: todayStr,
      scheduledStartTime: '09:00',
      scheduledEndTime: '17:00',
      status: 'CHECKED_OUT',
      approvalStatus: 'APPROVED',
      passBadgeNumber: 'V-BADGE-703',
      checkInTime: `${todayStr} 08:55:00`,
      checkOutTime: `${todayStr} 16:45:00`,
      checkInSecurityUserId: 'usr-sec-1',
      checkOutSecurityUserId: 'usr-sec-1',
      vehicleNumber: 'B-1102-M',
      itemsCarried: 'Dell XPS 15 Laptop',
      isBlacklistedAtRegistration: false,
      notes: 'Previous attendee - Apex Senior Analyst',
      createdAt: new Date().toISOString()
    },

    // DUMMY COMPANY 2: Cyberdyne Security Ltd (3 Visitors)
    {
      id: 'vis-cyb-1',
      registrationNo: 'VMS-2026-7002',
      fullName: 'Daniel Radcliffe',
      idNumber: 'IC-900315-14-7781',
      phone: '+60 11-1092 3341',
      email: 'd.radcliffe@cyberdyne.io',
      companyName: 'Cyberdyne Security Ltd',
      visitorCategoryId: 'vc-1',
      visitorCategoryName: 'Customer',
      purpose: 'Cybersecurity Incident Response Audit',
      hostUserId: 'usr-staff-1',
      hostUserName: 'John Miller',
      hostDepartment: 'Information Technology',
      meetingVenueId: 'mv-1',
      meetingVenueName: 'Executive Boardroom 1',
      scheduledDate: todayStr,
      scheduledStartTime: '10:00',
      scheduledEndTime: '16:00',
      status: 'CHECKED_OUT',
      approvalStatus: 'APPROVED',
      passBadgeNumber: 'V-BADGE-704',
      checkInTime: `${todayStr} 09:45:00`,
      checkOutTime: `${todayStr} 15:50:00`,
      checkInSecurityUserId: 'usr-sec-1',
      checkOutSecurityUserId: 'usr-sec-1',
      vehicleNumber: 'CYB-9021',
      itemsCarried: 'Lenovo ThinkPad P1 Workstation',
      isBlacklistedAtRegistration: false,
      notes: 'Previous attendee - Chief Security Auditor',
      createdAt: new Date().toISOString()
    },
    {
      id: 'vis-cyb-2',
      registrationNo: 'VMS-2026-7002',
      fullName: 'Elena Rostova',
      idNumber: 'IC-941102-08-4410',
      phone: '+60 17-882 1190',
      email: 'elena.rostova@cyberdyne.io',
      companyName: 'Cyberdyne Security Ltd',
      visitorCategoryId: 'vc-1',
      visitorCategoryName: 'Customer',
      purpose: 'Cybersecurity Incident Response Audit',
      hostUserId: 'usr-staff-1',
      hostUserName: 'John Miller',
      hostDepartment: 'Information Technology',
      meetingVenueId: 'mv-1',
      meetingVenueName: 'Executive Boardroom 1',
      scheduledDate: todayStr,
      scheduledStartTime: '10:00',
      scheduledEndTime: '16:00',
      status: 'CHECKED_OUT',
      approvalStatus: 'APPROVED',
      passBadgeNumber: 'V-BADGE-705',
      checkInTime: `${todayStr} 09:48:00`,
      checkOutTime: `${todayStr} 15:50:00`,
      checkInSecurityUserId: 'usr-sec-1',
      checkOutSecurityUserId: 'usr-sec-1',
      vehicleNumber: 'W-7711-K',
      itemsCarried: 'Asus ROG Zephyrus Laptop',
      isBlacklistedAtRegistration: false,
      notes: 'Previous attendee - Threat Intelligence Lead',
      createdAt: new Date().toISOString()
    },
    {
      id: 'vis-cyb-3',
      registrationNo: 'VMS-2026-7002',
      fullName: 'Frank Castle',
      idNumber: 'IC-870622-10-5112',
      phone: '+60 12-990 4421',
      email: 'f.castle@cyberdyne.io',
      companyName: 'Cyberdyne Security Ltd',
      visitorCategoryId: 'vc-1',
      visitorCategoryName: 'Customer',
      purpose: 'Cybersecurity Incident Response Audit',
      hostUserId: 'usr-staff-1',
      hostUserName: 'John Miller',
      hostDepartment: 'Information Technology',
      meetingVenueId: 'mv-1',
      meetingVenueName: 'Executive Boardroom 1',
      scheduledDate: todayStr,
      scheduledStartTime: '10:00',
      scheduledEndTime: '16:00',
      status: 'CHECKED_OUT',
      approvalStatus: 'APPROVED',
      passBadgeNumber: 'V-BADGE-706',
      checkInTime: `${todayStr} 09:50:00`,
      checkOutTime: `${todayStr} 15:50:00`,
      checkInSecurityUserId: 'usr-sec-1',
      checkOutSecurityUserId: 'usr-sec-1',
      vehicleNumber: 'KV-3301',
      itemsCarried: 'Ruggedized Fluke Tester, Laptop',
      isBlacklistedAtRegistration: false,
      notes: 'Previous attendee - Security Hardware Specialist',
      createdAt: new Date().toISOString()
    },

    // DUMMY COMPANY 3: NexGen Logistics Corp (3 Visitors)
    {
      id: 'vis-nxg-1',
      registrationNo: 'VMS-2026-7003',
      fullName: 'Grace Hopper',
      idNumber: 'IC-930818-14-1102',
      phone: '+60 13-441 9082',
      email: 'grace.hopper@nexgenlogistics.com',
      companyName: 'NexGen Logistics Corp',
      visitorCategoryId: 'vc-2',
      visitorCategoryName: 'Supplier',
      purpose: 'Supply Chain Integration Review',
      hostUserId: 'usr-staff-2',
      hostUserName: 'Sarah Jenkins',
      hostDepartment: 'Human Resources',
      meetingVenueId: 'mv-4',
      meetingVenueName: 'HR Recruitment Suite 202',
      scheduledDate: todayStr,
      scheduledStartTime: '11:00',
      scheduledEndTime: '14:00',
      status: 'CHECKED_OUT',
      approvalStatus: 'APPROVED',
      passBadgeNumber: 'V-BADGE-707',
      checkInTime: `${todayStr} 10:45:00`,
      checkOutTime: `${todayStr} 13:50:00`,
      checkInSecurityUserId: 'usr-sec-1',
      checkOutSecurityUserId: 'usr-sec-1',
      vehicleNumber: 'NXG-8819',
      itemsCarried: 'Barcode Scanner, Tablet',
      isBlacklistedAtRegistration: false,
      notes: 'Previous attendee - Logistics Director',
      createdAt: new Date().toISOString()
    },
    {
      id: 'vis-nxg-2',
      registrationNo: 'VMS-2026-7003',
      fullName: 'Henry Cavill',
      idNumber: 'IC-890411-01-6673',
      phone: '+60 18-221 0044',
      email: 'henry.cavill@nexgenlogistics.com',
      companyName: 'NexGen Logistics Corp',
      visitorCategoryId: 'vc-2',
      visitorCategoryName: 'Supplier',
      purpose: 'Supply Chain Integration Review',
      hostUserId: 'usr-staff-2',
      hostUserName: 'Sarah Jenkins',
      hostDepartment: 'Human Resources',
      meetingVenueId: 'mv-4',
      meetingVenueName: 'HR Recruitment Suite 202',
      scheduledDate: todayStr,
      scheduledStartTime: '11:00',
      scheduledEndTime: '14:00',
      status: 'CHECKED_OUT',
      approvalStatus: 'APPROVED',
      passBadgeNumber: 'V-BADGE-708',
      checkInTime: `${todayStr} 10:48:00`,
      checkOutTime: `${todayStr} 13:50:00`,
      checkInSecurityUserId: 'usr-sec-1',
      checkOutSecurityUserId: 'usr-sec-1',
      vehicleNumber: 'B-9988-P',
      itemsCarried: 'Microsoft Surface Pro 9',
      isBlacklistedAtRegistration: false,
      notes: 'Previous attendee - Fleet Operations Manager',
      createdAt: new Date().toISOString()
    },
    {
      id: 'vis-nxg-3',
      registrationNo: 'VMS-2026-7003',
      fullName: 'Isabel Mercer',
      idNumber: 'IC-951230-10-2290',
      phone: '+60 14-771 8820',
      email: 'isabel.mercer@nexgenlogistics.com',
      companyName: 'NexGen Logistics Corp',
      visitorCategoryId: 'vc-2',
      visitorCategoryName: 'Supplier',
      purpose: 'Supply Chain Integration Review',
      hostUserId: 'usr-staff-2',
      hostUserName: 'Sarah Jenkins',
      hostDepartment: 'Human Resources',
      meetingVenueId: 'mv-4',
      meetingVenueName: 'HR Recruitment Suite 202',
      scheduledDate: todayStr,
      scheduledStartTime: '11:00',
      scheduledEndTime: '14:00',
      status: 'CHECKED_OUT',
      approvalStatus: 'APPROVED',
      passBadgeNumber: 'V-BADGE-709',
      checkInTime: `${todayStr} 10:50:00`,
      checkOutTime: `${todayStr} 13:50:00`,
      checkInSecurityUserId: 'usr-sec-1',
      checkOutSecurityUserId: 'usr-sec-1',
      vehicleNumber: 'W-1234-Z',
      itemsCarried: 'HP ZBook Workstation',
      isBlacklistedAtRegistration: false,
      notes: 'Previous attendee - Supply Chain Data Engineer',
      createdAt: new Date().toISOString()
    }
  ],

  contractors: [
    {
      id: 'ctr-101',
      registrationNo: 'CTR-2026-9001',
      fullName: 'Viktor Vance (Lead Electrician)',
      idNumber: 'CTR-771029',
      phone: '+1 555-0182',
      email: 'viktor@volttech-engineering.com',
      companyName: 'VoltTech Engineering Solutions',
      workOrderNo: 'WO-8821',
      contractorCategoryId: 'cc-2',
      contractorCategoryName: 'Electrical Works',
      workScope: 'High Voltage Transformer Maintenance & Circuit Breaker Test',
      hostUserId: 'usr-staff-1',
      hostUserName: 'John Miller',
      hostDepartment: 'Information Technology',
      locationVenueId: 'mv-5',
      locationVenueName: 'Facility Maintenance Bay & Server Room Substation',
      startDate: todayStr,
      endDate: todayStr,
      startTime: '08:00',
      endTime: '17:00',
      status: 'PENDING_APPROVAL',
      approvalStatus: 'PENDING',
      safetyInductionVerified: true,
      passBadgeNumber: null,
      checkInTime: null,
      checkOutTime: null,
      vehicleNumber: 'VAN-8810',
      toolsEquipmentCarried: 'Insulated Tool Kit, Voltage Calibrator',
      isForeignWorker: true,
      passportNumber: 'B-8839210',
      nationality: 'Indonesian',
      permitNumber: 'PLKS-MY-2026-8812',
      permitExpiryDate: '2026-12-31',
      permitStatus: 'VALID',
      createdAt: new Date().toISOString()
    },
    {
      id: 'ctr-103',
      registrationNo: 'CTR-2026-9003',
      fullName: 'Rajesh Kumar (HVAC Specialist)',
      idNumber: 'P-9928104',
      phone: '+60 11-2390 8812',
      email: 'rajesh@cooltech-hvac.com',
      companyName: 'CoolTech HVAC Engineering',
      workOrderNo: 'WO-9945',
      contractorCategoryId: 'cc-2',
      contractorCategoryName: 'Mechanical',
      workScope: 'Chiller Unit Overhaul & Refrigerant Gas Refill',
      hostUserId: 'usr-staff-1',
      hostUserName: 'John Miller',
      hostDepartment: 'Information Technology',
      locationVenueId: 'mv-5',
      locationVenueName: 'Facility Maintenance Bay',
      startDate: todayStr,
      endDate: todayStr,
      startTime: '08:00',
      endTime: '17:00',
      status: 'PENDING_APPROVAL',
      approvalStatus: 'PENDING',
      safetyInductionVerified: true,
      passBadgeNumber: null,
      checkInTime: null,
      checkOutTime: null,
      vehicleNumber: 'LORRY-7721',
      toolsEquipmentCarried: 'Gas Cylinders, Pressure Gauges, Vacuum Pump',
      isForeignWorker: true,
      passportNumber: 'P-9928104',
      nationality: 'Indian',
      permitNumber: 'PLKS-2026-MY99',
      permitExpiryDate: '2027-06-15',
      permitStatus: 'VALID',
      createdAt: new Date().toISOString()
    },
    {
      id: 'ctr-104',
      registrationNo: 'CTR-2026-9004',
      fullName: 'Budi Santoso (Senior Chiller Tech)',
      idNumber: 'B-7712901',
      phone: '+60 17-8821 003',
      email: 'budi@cooltech-hvac.com',
      companyName: 'CoolTech HVAC Engineering',
      workOrderNo: 'WO-9945',
      contractorCategoryId: 'cc-2',
      contractorCategoryName: 'Mechanical',
      workScope: 'AHU Ducting Clean & Air Filter Replacement',
      hostUserId: 'usr-staff-1',
      hostUserName: 'John Miller',
      hostDepartment: 'Information Technology',
      locationVenueId: 'mv-5',
      locationVenueName: 'Facility Maintenance Bay',
      startDate: todayStr,
      endDate: todayStr,
      startTime: '08:00',
      endTime: '17:00',
      status: 'SCHEDULED',
      approvalStatus: 'APPROVED',
      approvedByUserId: 'usr-md-1',
      approvedByUserName: 'Tanaka Kenji (Managing Director)',
      approvedAt: `${todayStr} 08:30:00`,
      safetyInductionVerified: true,
      passBadgeNumber: null,
      checkInTime: null,
      checkOutTime: null,
      vehicleNumber: 'LORRY-7721',
      toolsEquipmentCarried: 'AHU Filter Packs, Duct Inspection Camera',
      isForeignWorker: true,
      passportNumber: 'B-7712901',
      nationality: 'Indonesian',
      permitNumber: 'PLKS-2026-ID88',
      permitExpiryDate: '2026-11-20',
      permitStatus: 'VALID',
      createdAt: new Date().toISOString()
    },
    {
      id: 'ctr-105',
      registrationNo: 'CTR-2026-9005',
      fullName: 'Tariqul Islam (HVAC Technician)',
      idNumber: 'A-4412903',
      phone: '+60 19-3382 109',
      email: 'tariqul@cooltech-hvac.com',
      companyName: 'CoolTech HVAC Engineering',
      workOrderNo: 'WO-9945',
      contractorCategoryId: 'cc-2',
      contractorCategoryName: 'Mechanical',
      workScope: 'Cooling Tower Servicing',
      hostUserId: 'usr-staff-1',
      hostUserName: 'John Miller',
      hostDepartment: 'Information Technology',
      locationVenueId: 'mv-5',
      locationVenueName: 'Rooftop Cooling Tower Bay',
      startDate: todayStr,
      endDate: todayStr,
      startTime: '08:00',
      endTime: '17:00',
      status: 'SCHEDULED',
      approvalStatus: 'APPROVED',
      approvedByUserId: 'usr-md-1',
      approvedByUserName: 'Tanaka Kenji (Managing Director)',
      approvedAt: `${todayStr} 08:30:00`,
      safetyInductionVerified: true,
      passBadgeNumber: null,
      checkInTime: null,
      checkOutTime: null,
      vehicleNumber: 'VAN-9922',
      toolsEquipmentCarried: 'High Pressure Hose, Safety Harness',
      isForeignWorker: true,
      passportNumber: 'A-4412903',
      nationality: 'Bangladeshi',
      permitNumber: 'PLKS-MY-2026-9912',
      permitExpiryDate: '2027-03-10',
      permitStatus: 'VALID',
      createdAt: new Date().toISOString()
    },
    {
      id: 'ctr-106',
      registrationNo: 'CTR-2026-9006',
      fullName: 'Nguyen Van Minh (Safety Supervisor)',
      idNumber: 'V-9918230',
      phone: '+60 12-7712 994',
      email: 'minh@apex-fire-safety.com',
      companyName: 'Apex Fire & Safety Services',
      workOrderNo: 'WO-9912',
      contractorCategoryId: 'cc-1',
      contractorCategoryName: 'Fire Safety & Mechanical',
      workScope: 'Fire Sprinkler Valve Calibrations',
      hostUserId: 'usr-staff-2',
      hostUserName: 'Sarah Jenkins',
      hostDepartment: 'Human Resources',
      locationVenueId: 'mv-2',
      locationVenueName: 'Main Riser & Plant Room',
      startDate: todayStr,
      endDate: todayStr,
      startTime: '08:00',
      endTime: '17:00',
      status: 'SCHEDULED',
      approvalStatus: 'APPROVED',
      approvedByUserId: 'usr-md-1',
      approvedByUserName: 'Tanaka Kenji (Managing Director)',
      approvedAt: `${todayStr} 08:00:00`,
      safetyInductionVerified: true,
      passBadgeNumber: null,
      checkInTime: null,
      checkOutTime: null,
      vehicleNumber: 'TRK-5520',
      toolsEquipmentCarried: 'Calibrated Flow Meters',
      isForeignWorker: true,
      passportNumber: 'V-9918230',
      nationality: 'Vietnamese',
      permitNumber: 'PLKS-MY-2026-7710',
      permitExpiryDate: '2026-10-15',
      permitStatus: 'VALID',
      createdAt: new Date().toISOString()
    },
    {
      id: 'ctr-107',
      registrationNo: 'CTR-2026-9007',
      fullName: 'Arjun Sharma (Electrical Assistant)',
      idNumber: 'N-5521094',
      phone: '+60 14-8891 002',
      email: 'arjun@volttech-engineering.com',
      companyName: 'VoltTech Engineering Solutions',
      workOrderNo: 'WO-8821',
      contractorCategoryId: 'cc-1',
      contractorCategoryName: 'Electrical Works',
      workScope: 'Substation Cable Trench Wiring',
      hostUserId: 'usr-staff-1',
      hostUserName: 'John Miller',
      hostDepartment: 'Information Technology',
      locationVenueId: 'mv-5',
      locationVenueName: 'Facility Maintenance Bay',
      startDate: todayStr,
      endDate: todayStr,
      startTime: '08:00',
      endTime: '17:00',
      status: 'SCHEDULED',
      approvalStatus: 'APPROVED',
      approvedByUserId: 'usr-md-1',
      approvedByUserName: 'Tanaka Kenji (Managing Director)',
      approvedAt: `${todayStr} 08:00:00`,
      safetyInductionVerified: true,
      passBadgeNumber: null,
      checkInTime: null,
      checkOutTime: null,
      vehicleNumber: 'VAN-8810',
      toolsEquipmentCarried: 'Crimping Tools, Insulation Testers',
      isForeignWorker: true,
      passportNumber: 'N-5521094',
      nationality: 'Nepalese',
      permitNumber: 'PLKS-2026-NP44',
      permitExpiryDate: '2027-01-20',
      permitStatus: 'VALID',
      createdAt: new Date().toISOString()
    },
    {
      id: 'ctr-108',
      registrationNo: 'CTR-2026-9008',
      fullName: 'Siti Rahma (CleanPro Lead)',
      idNumber: 'C-1190283',
      phone: '+60 16-3390 118',
      email: 'siti.rahma@cleanpro.com',
      companyName: 'CleanPro Facility Solutions',
      workOrderNo: 'WO-5510',
      contractorCategoryId: 'cc-3',
      contractorCategoryName: 'Cleaning',
      workScope: 'Deep Chemical Cleaning & Sanitization',
      hostUserId: 'usr-staff-1',
      hostUserName: 'John Miller',
      hostDepartment: 'Information Technology',
      locationVenueId: 'mv-1',
      locationVenueName: 'Executive Boardroom 1',
      startDate: todayStr,
      endDate: todayStr,
      startTime: '08:00',
      endTime: '17:00',
      status: 'SCHEDULED',
      approvalStatus: 'APPROVED',
      approvedByUserId: 'usr-md-1',
      approvedByUserName: 'Tanaka Kenji (Managing Director)',
      approvedAt: `${todayStr} 08:00:00`,
      safetyInductionVerified: true,
      passBadgeNumber: null,
      checkInTime: null,
      checkOutTime: null,
      vehicleNumber: 'VAN-2201',
      toolsEquipmentCarried: 'Industrial Steam Cleaners',
      isForeignWorker: true,
      passportNumber: 'C-1190283',
      nationality: 'Indonesian',
      permitNumber: 'PLKS-2026-MY11',
      permitExpiryDate: '2026-12-15',
      permitStatus: 'VALID',
      createdAt: new Date().toISOString()
    },
    {
      id: 'ctr-102',
      registrationNo: 'CTR-2026-9002',
      fullName: 'Ahmad Hassan',
      idNumber: 'CTR-441092',
      phone: '+1 555-0199',
      email: 'ahmad@apex-fire-safety.com',
      companyName: 'Apex Fire & Safety Services',
      workOrderNo: 'WO-9912',
      contractorCategoryId: 'cc-1',
      contractorCategoryName: 'Fire Safety & Mechanical',
      workScope: 'Quarterly Fire Suppression Pressure Testing',
      hostUserId: 'usr-staff-2',
      hostUserName: 'Sarah Jenkins',
      hostDepartment: 'Human Resources',
      locationVenueId: 'mv-2',
      locationVenueName: 'Conference Room B & Main Riser',
      startDate: todayStr,
      endDate: todayStr,
      startTime: '08:00',
      endTime: '17:00',
      status: 'SCHEDULED',
      approvalStatus: 'APPROVED',
      approvedByUserId: 'usr-md-1',
      approvedByUserName: 'Tanaka Kenji (Managing Director)',
      approvedAt: `${todayStr} 08:00:00`,
      safetyInductionVerified: true,
      passBadgeNumber: null,
      checkInTime: null,
      checkOutTime: null,
      vehicleNumber: 'TRK-5520',
      toolsEquipmentCarried: 'Pressure Gauges, CO2 Tanks',
      createdAt: new Date().toISOString()
    }
  ],

  blacklist: [],

  auditLogs: [],

  loginHistory: [],

  settings: {
    companyName: 'Enterprise Headquarters Corp',
    passPrefixVisitor: 'V-BADGE-',
    passPrefixContractor: 'C-BADGE-',
    maxDailyVisitors: 150,
    autoCheckOutGraceHours: 12,
    requireIdVerification: true,
    requireVehicleRecord: true,
    allowSelfCheckout: false,
    onPremiseNoticeText: 'All visitors must display their physical badge visibly at all times while on company premises. Photography prohibited without written clearance.'
  },

  passwordPolicy: {
    minLength: 10,
    requireUppercase: true,
    requireNumbers: true,
    requireSpecialChar: true,
    expirationDays: 90,
    maxFailedAttempts: 5
  }
};

import { saveAuditLogToPg } from './postgres';

export function logAudit(
  userId: string,
  action: string,
  details: string,
  req?: any,
  ipOverride?: string
) {
  const user = db.users.find(u => u.id === userId);
  const userAgent = req?.headers?.['user-agent'] || '';

  let computerName = 'SEC-WORKSTATION-01';
  if (userAgent.includes('Windows')) computerName = 'WIN10-ENT-WORKSTATION';
  else if (userAgent.includes('Macintosh')) computerName = 'MAC-SEC-TERMINAL';
  else if (userAgent.includes('Linux')) computerName = 'LINUX-SEC-NODE';
  else if (userAgent.includes('iPhone') || userAgent.includes('Android')) computerName = 'GATE-PASS-MOBILE';

  let category: 'User' | 'Security' | 'Visitor' | 'Contractor' | 'System' = 'System';
  const act = action.toUpperCase();
  if (act.includes('LOGIN') || act.includes('LOGOUT') || act.includes('SWITCH') || act.includes('BLACKLIST') || act.includes('PASSWORD') || act.includes('POLICY') || act.includes('SECURITY')) {
    category = 'Security';
  } else if (act.includes('USER')) {
    category = 'User';
  } else if (act.includes('VISITOR')) {
    category = 'Visitor';
  } else if (act.includes('CONTRACTOR')) {
    category = 'Contractor';
  }

  const resolvedIp = ipOverride || req?.headers?.['x-forwarded-for'] as string || req?.socket?.remoteAddress || '192.168.10.100';

  const newLog: AuditLog = {
    id: `log-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
    timestamp: new Date().toISOString().replace('T', ' ').substring(0, 19),
    userId,
    userName: user ? user.fullName : 'System',
    userRole: user ? user.role : 'ADMINISTRATOR',
    action,
    details,
    ipAddress: resolvedIp,
    computerName,
    category
  };

  db.auditLogs.unshift(newLog);
  saveAuditLogToPg(newLog).catch(err => console.error('PG audit log save error:', err));
}
